# Generated by Django 3.1.2 on 2021-03-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=1000)),
                ('contact_number', models.IntegerField()),
            ],
        ),
    ]
