# Generated by Django 3.1.2 on 2021-03-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hall_link',
            field=models.CharField(default='https://zoom.us/j/98922319654?pwd=MXVDNEJCOGppeU1pbWtrMkZsNWlLUT09', max_length=200),
        ),
    ]
