# Generated by Django 3.1.2 on 2020-12-15 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_delete_student'),
        ('account', '0002_auto_20201215_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_helper',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('oc', 'oc')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.player'),
        ),
    ]
