# Generated by Django 3.1.2 on 2020-12-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201215_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='player_id',
            new_name='player',
        ),
    ]
