# Generated by Django 3.1.2 on 2021-02-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210227_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='profile/person.png', null=True, upload_to='profile/'),
        ),
    ]
