# Generated by Django 3.1.2 on 2021-03-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210228_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
    ]
