# Generated by Django 3.1.2 on 2020-12-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201215_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('oc', 'oc'), ('admin', 'admin')], max_length=10, null=True),
        ),
    ]
