# Generated by Django 3.1.2 on 2020-12-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201216_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='player',
        ),
    ]
