# Generated by Django 4.1.2 on 2023-02-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booth", old_name="academic_levle", new_name="academic_level",
        ),
    ]
