# Generated by Django 4.1.2 on 2023-02-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0002_rename_academic_levle_booth_academic_level"),
    ]

    operations = [
        migrations.RemoveField(model_name="booth", name="joy_score",),
        migrations.RemoveField(model_name="boothrequirement", name="joy_score",),
        migrations.RemoveField(model_name="boothscoring", name="joy_score",),
    ]
