# Generated by Django 4.1.2 on 2023-03-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0003_remove_booth_joy_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boothrequirement",
            name="display_name",
            field=models.CharField(default="Display name", max_length=100),
            preserve_default=False,
        ),
    ]
