# Generated by Django 4.2.19 on 2025-02-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0003_alter_transaction_booth_alter_transaction_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="academic_level",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "無學歷"),
                    (1, "小學畢業"),
                    (2, "中學畢業"),
                    (3, "大專畢業"),
                    (4, "大學畢業"),
                ],
                max_length=1,
                null=True,
                verbose_name="學歷",
            ),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="academic_level",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "無學歷"),
                    (1, "小學畢業"),
                    (2, "中學畢業"),
                    (3, "大專畢業"),
                    (4, "大學畢業"),
                ],
                default=0,
                max_length=1,
                null=True,
                verbose_name="學歷",
            ),
        ),
    ]
