# Generated by Django 4.1.2 on 2023-03-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0004_boothrequirement_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="boothscoring",
            name="display_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
