# Generated by Django 4.2.19 on 2025-02-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0005_alter_player_born_academic_level"),
        ("booth", "0005_alter_booth_academic_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="booth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participation_booth",
                to="booth.booth",
                verbose_name="攤位",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participation_player",
                to="player.player",
                verbose_name="玩家",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_player",
                to="player.player",
                verbose_name="玩家",
            ),
        ),
    ]
