# Generated by Django 2.2.7 on 2021-11-01 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_auto_20211031_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='booth_admins',
            field=models.ManyToManyField(blank=True, related_name='booth_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
