# Generated by Django 4.1.2 on 2024-01-20 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("player", "0010_delete_bornstatus"),
        ("booth", "0005_boothscoring_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="saving",
            field=models.IntegerField(default=0, verbose_name="銀行存款"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="participation",
            name="booth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booth.booth",
                verbose_name="攤位",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="marker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="評分員",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="player.player",
                verbose_name="玩家",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="record_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="時間"),
        ),
        migrations.AlterField(
            model_name="participation",
            name="remarks",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="評語"
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booth.boothscoring",
                verbose_name="分數",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="booth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booth.booth",
                verbose_name="攤位",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="marker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="評分員",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="money",
            field=models.IntegerField(verbose_name="金錢"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="player.player",
                verbose_name="玩家",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="record_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="時間"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="remarks",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="備註"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("pay", "付款"), ("receive", "收款")],
                max_length=10,
                verbose_name="交易類型",
            ),
        ),
    ]
