# Generated by Django 4.1.2 on 2022-10-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0006_auto_20211101_2142"),
    ]

    operations = [
        migrations.AddField(
            model_name="boothscoring",
            name="academic_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boothscoring",
            name="growth_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boothscoring",
            name="health_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boothscoring",
            name="joy_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boothscoring",
            name="money",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boothscoring",
            name="relationship_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
