# Generated by Django 4.2.19 on 2025-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0006_alter_participation_booth_alter_participation_player_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="money",
            field=models.FloatField(default=0, verbose_name="金錢"),
        ),
    ]
