# Generated by Django 4.1.2 on 2023-01-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0007_boothscoring_academic_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boothrequirement",
            old_name="overall_score",
            new_name="academic_score",
        ),
        migrations.AddField(
            model_name="boothrequirement",
            name="growth_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boothrequirement",
            name="health_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boothrequirement",
            name="joy_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boothrequirement",
            name="money",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boothrequirement",
            name="relationship_score",
            field=models.IntegerField(default=0),
        ),
    ]
