# Generated by Django 4.1.2 on 2024-01-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0007_remove_transaction_saving_boothscoring_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boothscoring",
            name="display_name",
        ),
        migrations.AlterField(
            model_name="booth",
            name="academic_level",
            field=models.IntegerField(blank=True, null=True, verbose_name="學歷"),
        ),
        migrations.AlterField(
            model_name="booth",
            name="growth_score",
            field=models.IntegerField(blank=True, null=True, verbose_name="成長分數"),
        ),
        migrations.AlterField(
            model_name="booth",
            name="health_score",
            field=models.IntegerField(blank=True, null=True, verbose_name="健康分數"),
        ),
        migrations.AlterField(
            model_name="booth",
            name="money",
            field=models.IntegerField(blank=True, null=True, verbose_name="金錢"),
        ),
        migrations.AlterField(
            model_name="booth",
            name="relationship_score",
            field=models.IntegerField(blank=True, null=True, verbose_name="關係分數"),
        ),
        migrations.AlterField(
            model_name="booth",
            name="skill_score",
            field=models.IntegerField(blank=True, null=True, verbose_name="技能分數"),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="academic_level",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="學歷"
            ),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="growth_score",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="成長分數"
            ),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="health_score",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="健康分數"
            ),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="money",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="金錢"
            ),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="relationship_score",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="關係分數"
            ),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="skill_score",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="技能分數"
            ),
        ),
    ]
