# Generated by Django 4.1.2 on 2024-01-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0008_remove_boothscoring_display_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booth",
            name="score_options",
        ),
        migrations.AddField(
            model_name="boothscoring",
            name="booth",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booth.booth",
                verbose_name="攤位",
            ),
            preserve_default=False,
        ),
    ]
