# Generated by Django 4.1.2 on 2023-01-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0008_rename_overall_score_boothrequirement_academic_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="booth", name="score_options",),
        migrations.RemoveField(model_name="booth", name="url",),
        migrations.AddField(
            model_name="booth",
            name="academic_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booth",
            name="growth_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booth",
            name="health_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booth",
            name="joy_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booth",
            name="money",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booth",
            name="relationship_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
