# Generated by Django 4.2.19 on 2025-02-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0008_remove_participation_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothscoring",
            name="booth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booth_scoring",
                to="booth.booth",
                verbose_name="攤位",
            ),
        ),
    ]
