# Generated by Django 4.2.19 on 2025-02-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0009_alter_boothscoring_booth"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="name",
            field=models.CharField(
                default="參加", max_length=50, verbose_name="分數名稱"
            ),
            preserve_default=False,
        ),
    ]
