# Generated by Django 4.1.2 on 2023-01-15 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0008_remove_player_instructor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booth", "0009_remove_booth_score_options_remove_booth_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("record_time", models.DateTimeField(auto_now_add=True)),
                ("money", models.IntegerField()),
                ("remarks", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="player.player"
                    ),
                ),
            ],
        ),
    ]
