# Generated by Django 4.1.2 on 2024-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0009_remove_booth_score_options_boothscoring_booth"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bank_deposit",
            field=models.IntegerField(default=1, verbose_name="銀行存款"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="flat",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="樓宇"
            ),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="steps",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="步數"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("pay", "付款"),
                    ("receive", "收款"),
                    ("deposit", "存款"),
                    ("withdrawl", "提款"),
                ],
                max_length=10,
                verbose_name="交易類型",
            ),
        ),
    ]
