# Generated by Django 4.1.2 on 2023-01-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0010_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="score_options",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booth.boothscoring",
            ),
            preserve_default=False,
        ),
    ]
