# Generated by Django 4.1.2 on 2024-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0011_remove_transaction_bank_deposit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("pay", "付款"),
                    ("receive", "收款"),
                    ("deposit", "存款"),
                    ("withdrawal", "提款"),
                ],
                max_length=10,
                verbose_name="交易類型",
            ),
        ),
    ]
