# Generated by Django 4.1.2 on 2023-01-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0011_booth_score_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="booth", name="score_options",),
        migrations.AddField(
            model_name="booth",
            name="score_options",
            field=models.ManyToManyField(
                blank=True, related_name="booth_scores", to="booth.boothscoring"
            ),
        ),
    ]
