# Generated by Django 4.1.2 on 2024-02-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0012_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="name",
            field=models.CharField(max_length=50, verbose_name="攤位名稱"),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="name",
            field=models.CharField(max_length=50, verbose_name="分數名稱"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="interest_rate",
            field=models.FloatField(blank=True, default=0, verbose_name="利率"),
        ),
    ]
