# Generated by Django 4.1.2 on 2023-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0012_remove_booth_score_options_booth_score_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("pay", "pay"), ("receive", "receive")],
                default="pay",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
