# Generated by Django 4.1.2 on 2024-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0013_alter_booth_name_alter_boothscoring_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booth",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
