# Generated by Django 4.1.2 on 2024-02-04 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0014_alter_booth_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 4, 8, 41, 2, 62787, tzinfo=datetime.timezone.utc
                ),
                verbose_name="時間",
            ),
        ),
    ]
