# Generated by Django 4.1.2 on 2024-02-26 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0023_alter_boothscoring_record_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boothscoring",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 26, 0, 31, 25, 698468, tzinfo=datetime.timezone.utc
                ),
                verbose_name="時間",
            ),
        ),
        migrations.AlterField(
            model_name="boothscoring",
            name="steps",
            field=models.IntegerField(
                blank=True, default=-1, null=True, verbose_name="步數"
            ),
        ),
        migrations.AlterField(
            model_name="boothtraffic",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 26, 0, 31, 25, 698468, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 26, 0, 31, 25, 698468, tzinfo=datetime.timezone.utc
                ),
                verbose_name="時間",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 26, 0, 31, 25, 698468, tzinfo=datetime.timezone.utc
                ),
                verbose_name="時間",
            ),
        ),
    ]
