# Generated by Django 4.1.2 on 2023-02-07 15:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BornStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("health_score", models.IntegerField()),
                ("skill_score", models.IntegerField()),
                ("growth_score", models.IntegerField()),
                ("relationship_score", models.IntegerField()),
                ("joy_score", models.IntegerField()),
                ("money", models.IntegerField()),
                ("academic_level", models.IntegerField()),
                ("steps", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("level", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "live_status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=8,
                    ),
                ),
                (
                    "born_education_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player.education",
                    ),
                ),
                (
                    "born_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player.bornstatus",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstructorScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("comments", models.TextField(blank=True, max_length=1000, null=True)),
                ("record_time", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="player.player"
                    ),
                ),
            ],
        ),
    ]
