# Generated by Django 4.1.2 on 2025-02-05 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorscore",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2025, 2, 5, 16, 47, 32, 537424, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
