# Generated by Django 4.1.2 on 2023-02-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="instructorscore", name="instructor",),
    ]
