# Generated by Django 2.2.7 on 2021-10-31 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_remove_participation_verified'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='born_education_level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='born_status',
        ),
        migrations.RemoveField(
            model_name='player',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='player',
            name='live_status',
        ),
        migrations.AddField(
            model_name='player',
            name='debriefing_booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booth.Booth'),
        ),
    ]
