# Generated by Django 4.1.2 on 2025-02-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_alter_instructorscore_record_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InstructorScore",
        ),
    ]
