# Generated by Django 4.1.2 on 2022-10-30 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("player", "0002_auto_20211031_1345"),
    ]

    operations = [
        migrations.RemoveField(model_name="bornstatus", name="overall_score",),
        migrations.AddField(
            model_name="bornstatus",
            name="academic_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bornstatus",
            name="growth_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bornstatus",
            name="health_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bornstatus",
            name="joy_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bornstatus",
            name="money",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bornstatus",
            name="relationship_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="born_education_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="player.education",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="born_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="player.bornstatus",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="live_status",
            field=models.CharField(
                choices=[("active", "active"), ("inactive", "inactive")],
                default="active",
                max_length=8,
            ),
        ),
    ]
