# Generated by Django 4.1.2 on 2023-02-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_remove_instructorscore_instructor"),
    ]

    operations = [
        migrations.RemoveField(model_name="bornstatus", name="joy_score",),
    ]
