# Generated by Django 4.1.2 on 2023-02-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_bornstatus_joy_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='born_education_level',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
