# Generated by Django 4.1.2 on 2022-12-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0003_remove_bornstatus_overall_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="born_education_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="player.education",
            ),
        ),
    ]
