# Generated by Django 4.1.2 on 2022-12-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0005_alter_player_born_education_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="born_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="player.bornstatus",
            ),
        ),
    ]
