# Generated by Django 4.1.2 on 2023-01-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0006_alter_player_born_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="debriefing_booth",),
    ]
