# Generated by Django 4.1.2 on 2023-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0007_alter_player_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="born_academic_level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="born_defect",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="born_growth_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="born_health_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="born_money",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="born_relationship_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="born_skill_score",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="born_steps",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
