# Generated by Django 4.1.2 on 2023-01-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0007_remove_player_debriefing_booth"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="instructor",),
    ]
