# Generated by Django 4.1.2 on 2024-01-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0009_remove_player_born_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BornStatus",
        ),
    ]
