# Generated by Django 4.1.2 on 2024-02-04 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0010_delete_bornstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorscore",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 4, 8, 41, 2, 488767, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
