# Generated by Django 4.1.2 on 2024-02-20 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0011_alter_instructorscore_record_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="inactive_reason",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="instructorscore",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 20, 14, 57, 45, 521634, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
