# Generated by Django 4.1.2 on 2024-02-21 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0012_player_inactive_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorscore",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 21, 12, 42, 58, 904197, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
