# Generated by Django 4.1.2 on 2024-02-28 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0020_alter_instructorscore_record_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorscore",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 2, 28, 15, 59, 8, 610470, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
