# Generated by Django 5.0.3 on 2024-03-13 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0021_alter_instructorscore_record_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorscore",
            name="record_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 3, 13, 12, 47, 28, 589339, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
