# Generated by Django 3.1.2 on 2020-12-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='booth_id',
            new_name='booth',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='player_id',
            new_name='player',
        ),
    ]
