# Generated by Django 3.1.2 on 2020-12-19 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_auto_20201215_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothScoring',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('health_score', models.IntegerField()),
                ('academic_score', models.IntegerField()),
                ('growth_score', models.IntegerField()),
                ('relationship_score', models.IntegerField()),
                ('joy_score', models.IntegerField()),
                ('money', models.IntegerField()),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
            ],
        ),
    ]
