# Generated by Django 2.2.7 on 2021-10-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('booth', '0002_participation_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boothtraffic',
            name='user',
        ),
        migrations.AddField(
            model_name='boothtraffic',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
            preserve_default=False,
        ),
    ]
