# Generated by Django 3.1.2 on 2021-02-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_participation_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
