# Generated by Django 2.2.7 on 2021-10-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_auto_20211023_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='verified',
        ),
    ]
