# Generated by Django 3.1.2 on 2020-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_boothscoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothscoring',
            name='score_name',
            field=models.CharField(default='Done', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boothscoring',
            name='academic_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boothscoring',
            name='growth_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boothscoring',
            name='health_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boothscoring',
            name='joy_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boothscoring',
            name='money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boothscoring',
            name='relationship_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
