# Generated by Django 3.1.2 on 2020-12-19 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booth', '0004_auto_20201219_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='booth_admins',
            field=models.ManyToManyField(related_name='booth_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booth',
            name='booth_in_charge',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booth_in_charge', to='account.user'),
            preserve_default=False,
        ),
    ]
