# Generated by Django 3.1.2 on 2021-02-28 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booth', '0005_playervisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playervisit',
            name='player',
        ),
        migrations.AddField(
            model_name='playervisit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
    ]
