# Generated by Django 3.1.2 on 2020-12-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_auto_20201219_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boothscoring',
            name='booth',
        ),
    ]
