# Generated by Django 3.1.2 on 2021-02-28 02:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booth', '0006_auto_20210228_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerVisit',
            new_name='BoothTraffic',
        ),
    ]
