# Generated by Django 3.1.2 on 2020-12-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0007_auto_20201219_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
