# Generated by Django 3.1.2 on 2021-02-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0007_auto_20210228_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
