# Generated by Django 3.1.2 on 2021-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0008_auto_20210228_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booth',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
