# Generated by Django 3.1.2 on 2020-12-19 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booth', '0010_auto_20201219_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='booth_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booth_in_charge', to=settings.AUTH_USER_MODEL),
        ),
    ]
