# Generated by Django 3.1.2 on 2020-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0011_auto_20201219_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothRequirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('health_score', models.IntegerField(default=0)),
                ('academic_score', models.IntegerField(default=0)),
                ('growth_score', models.IntegerField(default=0)),
                ('relationship_score', models.IntegerField(default=0)),
                ('joy_score', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='participation',
            name='academic_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='growth_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='health_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='joy_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participation',
            name='relationship_score',
            field=models.IntegerField(default=0),
        ),
    ]
