# Generated by Django 3.1.2 on 2020-12-20 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0012_auto_20201220_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booth.boothrequirement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boothrequirement',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
