# Generated by Django 3.1.2 on 2020-12-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0013_auto_20201220_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='score_options',
            field=models.ManyToManyField(blank=True, null=True, related_name='booth_admins', to='booth.BoothScoring'),
        ),
    ]
