# Generated by Django 3.1.2 on 2020-12-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0014_booth_score_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='score_options',
            field=models.ManyToManyField(blank=True, null=True, related_name='score_options', to='booth.BoothScoring'),
        ),
    ]
