# Generated by Django 3.1.2 on 2020-12-22 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booth', '0015_auto_20201222_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='booth_admins',
            field=models.ManyToManyField(related_name='booth_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booth',
            name='score_options',
            field=models.ManyToManyField(related_name='score_options', to='booth.BoothScoring'),
        ),
    ]
