# Generated by Django 3.0.12 on 2021-02-12 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0017_auto_20210212_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
