# Generated by Django 3.0.12 on 2021-02-12 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0018_participation_record_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='overall_score',
        ),
        migrations.AddField(
            model_name='participation',
            name='score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booth.BoothScoring'),
            preserve_default=False,
        ),
    ]
