# Generated by Django 3.0.12 on 2021-02-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0019_auto_20210212_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
