# Generated by Django 3.0.12 on 2021-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0020_booth_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='requirement',
        ),
        migrations.AddField(
            model_name='booth',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
