# Generated by Django 3.0.12 on 2021-02-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0021_auto_20210215_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
