# Generated by Django 3.1.2 on 2020-12-14 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BornStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('health_score', models.IntegerField()),
                ('academic_score', models.IntegerField()),
                ('growth_score', models.IntegerField()),
                ('relationship_score', models.IntegerField()),
                ('joy_score', models.IntegerField()),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('live_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=8)),
                ('born_education_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.education')),
                ('born_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.bornstatus')),
            ],
        ),
    ]
