# Generated by Django 3.1.2 on 2020-12-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='player_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.player'),
            preserve_default=False,
        ),
    ]
