# Generated by Django 3.1.2 on 2020-12-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_student_player_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
