# Generated by Django 3.1.2 on 2020-12-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='born_education_level_id',
            new_name='born_education_level',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='born_status_id',
            new_name='born_status',
        ),
    ]
