# Generated by Django 3.1.2 on 2021-02-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_instructorscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorscore',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='instructorscore',
            name='player',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.player'),
            preserve_default=False,
        ),
    ]
