# Generated by Django 3.1.2 on 2021-02-27 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20210227_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorscore',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
