# Generated by Django 3.1.2 on 2020-12-19 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0005_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='past_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
