# Generated by Django 3.0.12 on 2021-02-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20201219_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bornstatus',
            name='academic_score',
        ),
        migrations.RemoveField(
            model_name='bornstatus',
            name='growth_score',
        ),
        migrations.RemoveField(
            model_name='bornstatus',
            name='health_score',
        ),
        migrations.RemoveField(
            model_name='bornstatus',
            name='joy_score',
        ),
        migrations.RemoveField(
            model_name='bornstatus',
            name='money',
        ),
        migrations.RemoveField(
            model_name='bornstatus',
            name='relationship_score',
        ),
        migrations.AddField(
            model_name='bornstatus',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
    ]
