# Generated by Django 4.1.2 on 2025-02-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructorgroup",
            name="students",
        ),
        migrations.RemoveField(
            model_name="user",
            name="room_no",
        ),
        migrations.AddField(
            model_name="user",
            name="instructor_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.instructorgroup",
            ),
            preserve_default=False,
        ),
    ]
