# Generated by Django 4.1.2 on 2025-02-07 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booth", "0001_initial"),
        (
            "account",
            "0002_remove_instructorgroup_students_remove_user_room_no_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="best_booth",
        ),
        migrations.CreateModel(
            name="BoothVoting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booth.booth"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "booth")},
            },
        ),
    ]
