# Generated by Django 4.1.2 on 2023-02-22 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_icon_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_id',
            field=models.CharField(default='5PPF9v1O1RiRNEwJ2i6y4JIaymPjabgm', max_length=32),
        ),
        migrations.CreateModel(
            name='InstructorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
