# Generated by Django 4.2.19 on 2025-02-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_user_best_booth_boothvoting"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorgroup",
            name="name",
            field=models.CharField(default="組別1", max_length=100),
            preserve_default=False,
        ),
    ]
