# Generated by Django 4.1.2 on 2023-02-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_encrypted_id_instructorgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encrypted_id',
            field=models.CharField(default='GSoY5j096m8gG6peVQMzbqy0uHz3NagC', max_length=32),
        ),
    ]
