# Generated by Django 4.1.2 on 2023-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_encrypted_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encrypted_id',
            field=models.CharField(default='8rm91lxLRRWE9kw2ZPkDYJt5XaSWQfyD', max_length=32),
        ),
    ]
