# Generated by Django 4.2.19 on 2025-02-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_instructorgroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="instructor_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_group_student",
                to="account.instructorgroup",
            ),
        ),
    ]
