# Generated by Django 4.2.19 on 2025-02-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_user_instructor_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="instructor_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_group_student",
                to="account.instructorgroup",
            ),
        ),
    ]
