# Generated by Django 4.1.2 on 2023-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_encrypted_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encrypted_id',
            field=models.CharField(default='flADf9XJZU4wkCBZTotNErt7MPKAqyO2', max_length=32),
        ),
    ]
