# Generated by Django 4.1.2 on 2023-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="o26ldMO9AxxdGadY0d6blPwvBTZabpQb", max_length=32
            ),
        ),
    ]
