# Generated by Django 4.1.2 on 2023-02-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="sElXwOzZQxe9FVtPq5xNq0DCVbdHiZHs", max_length=32
            ),
        ),
    ]
