# Generated by Django 4.1.2 on 2023-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="lU6toqmSjCOZJxXsMGnlRDNQCdtK53aU", max_length=32
            ),
        ),
    ]
