# Generated by Django 4.1.2 on 2023-02-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="UpkDbhbcpRrCkCbeU7VxNEp0sY2gjqLm", max_length=32
            ),
        ),
    ]
