# Generated by Django 4.1.2 on 2023-02-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="JqxtnOyHjTVCXUNCj0zPp73lJm3gRY26", max_length=32
            ),
        ),
    ]
