# Generated by Django 4.1.2 on 2023-02-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="school_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="mla1qGdcDRQzC4GeIxNeZwn0lPgwk9Hk", max_length=32
            ),
        ),
    ]
