# Generated by Django 4.1.2 on 2023-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_user_school_code_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="YEPHr4vOYGyoRQH2y2U38By7YYpbFLf1", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "student"),
                    ("oc", "oc"),
                    ("admin", "admin"),
                    ("instructor", "instructor"),
                    ("vip", "vip"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
