# Generated by Django 4.1.2 on 2023-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_alter_user_encrypted_id_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="OQfWTmJTtl28EdozjLcWM7OvZYvpZkqE", max_length=32
            ),
        ),
    ]
