# Generated by Django 4.1.2 on 2023-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="mkizV1T3poybhadHF7IGwoFRQZKMOuzN", max_length=32
            ),
        ),
    ]
