# Generated by Django 4.1.2 on 2023-03-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ["id"]},),
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="YOfBXvTmRXWZowOKiU73XuU1qlUHR6y7", max_length=32
            ),
        ),
    ]
