# Generated by Django 4.1.2 on 2023-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_alter_user_options_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="ggXuVkQtdh7DF8y6qQv5LprtmqCeg8P9", max_length=32
            ),
        ),
    ]
