# Generated by Django 4.1.2 on 2023-03-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="3JnkgXgumnARTobNegarNbn4pNyXQnDc", max_length=32
            ),
        ),
    ]
