# Generated by Django 4.1.2 on 2023-03-12 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_user_encrypted_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="instructorgroup", name="instructor",),
        migrations.AlterField(
            model_name="instructorgroup",
            name="students",
            field=models.ManyToManyField(
                related_name="student", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="FTuiMzu0wtvz7y9gVQoMuLxbmqkgqhjv", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="instructorgroup",
            name="instructor",
            field=models.ManyToManyField(
                related_name="instructor", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
