# Generated by Django 4.1.2 on 2024-01-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_remove_instructorgroup_instructor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="encrypted_id",
            field=models.CharField(
                default="WjFWZfeJBN9ECjKgsFLwMrfZNYLLnZxc", max_length=32
            ),
        ),
    ]
