# Generated by Django 4.1.2 on 2024-01-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_user_encrypted_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='encrypted_id',
            field=models.CharField(default='bCQm2RKCm8CvNeoKzVZNlcv0AhLoiQAU', max_length=32),
        ),
    ]
