# Generated by Django 4.1.2 on 2024-02-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0024_alter_user_best_booth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="room_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
