# Generated by Django 4.1.2 on 2024-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_user_room_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorgroup",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
