# Generated by Django 2.2.8 on 2021-04-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
