# Generated by Django 2.2.7 on 2021-10-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_remove_participation_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
