# Generated by Django 4.1.2 on 2023-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newscategory",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
