# Generated by Django 4.1.2 on 2024-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_remove_news_time_remove_news_url_alter_news_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image_url",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
