# Generated by Django 4.1.2 on 2024-02-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_news_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(default=1, upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
