# Generated by Django 5.0.3 on 2024-03-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
